name: ca_biositing_usda_census_view_1774996748
source:
  type: postgres
  connection:
    host: 127.0.0.1
    port: 5434
    database: biocirv-staging
    user: biocirv_readonly
    password: biocirv_dev_password
  table: usda_census_view
description: 'BioCirv view: ca_biositing.usda_census_view'
