name: ca_biositing_analysis_data_view_1775003978
source:
  type: parquet
  path: data.parquet
description: 'BioCirv view: ca_biositing.analysis_data_view'
columns:
- name: id
  type: string
- name: record_id
  type: string
- name: record_type
  type: string
- name: resource_id
  type: string
- name: resource
  type: string
- name: geoid
  type: string
- name: parameter
  type: string
- name: value
  type: string
- name: unit
  type: string
- name: dimension
  type: string
- name: dimension_value
  type: string
- name: dimension_unit
  type: string
